import os
path, dirs, files = next(os.walk("Coronahack-Chest-XRay-Dataset/train_data_seperated_into_individual_folders/Normal/"))
file_count = len(files)
print(file_count)
path, dirs, files = next(os.walk("Coronahack-Chest-XRay-Dataset/test_data_seperated_into_individual_folders/Normal/"))
file_count = len(files)
print(file_count)
path, dirs, files = next(os.walk("Coronahack-Chest-XRay-Dataset/test_data_seperated_into_individual_folders/Pnemonia bacteria"))
file_count = len(files)
print(file_count)
path, dirs, files = next(os.walk("Coronahack-Chest-XRay-Dataset/test_data_seperated_into_individual_folders/Pnemonia Virus"))
file_count = len(files)
print(file_count)